name: "Generar Snake"

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v2

      - name: Generar animación Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Lauty1550
          outputs: ./output/github-contribution-grid-snake.svg

      - name: Commit y push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Actualizar animación Snake"
          file_pattern: output/github-contribution-grid-snake.svg
